// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYZFj19kG4SZOguYfGE7K7H0LP-lWyFVA',
    appId: '1:617849013569:web:57d2e418052acdd14a8dc0',
    messagingSenderId: '617849013569',
    projectId: 'fir-memo-app-fa258',
    authDomain: 'fir-memo-app-fa258.firebaseapp.com',
    storageBucket: 'fir-memo-app-fa258.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bPVGeusQ1xR2Iw6N5tkoDCbds1oPqpw',
    appId: '1:617849013569:android:15b66ca3b310d5674a8dc0',
    messagingSenderId: '617849013569',
    projectId: 'fir-memo-app-fa258',
    storageBucket: 'fir-memo-app-fa258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0KMA4yGhj4rhcCxFphZvKoSkfycRyrqk',
    appId: '1:617849013569:ios:680b5de48718affe4a8dc0',
    messagingSenderId: '617849013569',
    projectId: 'fir-memo-app-fa258',
    storageBucket: 'fir-memo-app-fa258.appspot.com',
    iosClientId: '617849013569-pv2o2ovn55nt9isctji1s3uv9bligjpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0KMA4yGhj4rhcCxFphZvKoSkfycRyrqk',
    appId: '1:617849013569:ios:1c8900bc9294d3dc4a8dc0',
    messagingSenderId: '617849013569',
    projectId: 'fir-memo-app-fa258',
    storageBucket: 'fir-memo-app-fa258.appspot.com',
    iosClientId: '617849013569-bbaueer0i46gbkp6qt5a6220jhlj62mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFlutter.RunnerTests',
  );
}
